CC = gcc

CFLAGS = -Wall

all : ex1 ex2 ex3 ex4

ex1 : ex1.o

ex1.o : ex1.c

ex2: ex2.o

ex2.o : ex2.c

ex3 : ex3.o

ex3.o : ex3.c

ex4 : ex4.o

ex4.o : ex4.c

clean :
	@rm *.o
	@rm ex1
	@rm ex2
	@rm ex3
	@rm ex4

